name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting and formatting checks
        run: pnpm run lint

      - name: Check other file formatting (Prettier)
        run: pnpm exec prettier --check '**/*.{md,json,yaml,yml}'

      - name: Run type checking
        run: pnpm run type-check

      - name: Run build
        run: pnpm run build

      - name: Test CLI functionality
        run: |
          node dist/index.js --help
          node dist/index.js --version
